### ISSUE TITLE
GenerateTrainData.m file generate .bc files

### ISSUE THREAD

**Issue by Jcxloyal** [alfredtorres/3DFacePointCloudNet#7]
Hello friend, thank you for the impressive work! So I use the GenerateTrainData.m file to generate face scans, I got many .bc files, I have no idea how to open or read them, could you please give me some advice on how can I virtualize the face scans. Thanks a lot!

**Comment by alfredtorres** [comment]
There is a dataset py file in our project to describe how to build the pytorch dataset for our face dataset.
In the .py file there is a readbc or readbcn funtion.
I wish it helps you.
On 12/13/2021 ***@***.***> wrote：

Hello friend, thank you for the impressive work! So I use the GenerateTrainData.m file to generate face scans, I got many .bc files, I have no idea how to open or read them, could you please give me some advice on how can I virtualize the face scans. Thanks a lot!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Jcxloyal** [comment]
> There is a dataset py file in our project to describe how to build the pytorch dataset for our face dataset. In the .py file there is a readbc or readbcn funtion. I wish it helps you. On 12/13/2021 ***@***.***> wrote： Hello friend, thank you for the impressive work! So I use the GenerateTrainData.m file to generate face scans, I got many .bc files, I have no idea how to open or read them, could you please give me some advice on how can I virtualize the face scans. Thanks a lot! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Thank you so much!
